version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/app:/usr/share/nginx/app
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
      - api

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  pgadmin4:
    image: dpage/pgadmin4
    volumes:
      - ./pgadmin4/config.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: rootpass

      # 下記の設定によりログインを短縮
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5050:80"
    depends_on:
      - db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/components:/components
      - ./api/api.py:/api.py
      - ./api/requirements.txt:/requirements.txt
    ports:
      - "3000:3000"
    depends_on:
      - db