version: '3.8'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/api.py:/api.py
      - ./api/requirements.txt:/requirements.txt
    ports:
      - "8000:8000"